### ISSUE TITLE
Can't open sile.pdf

### ISSUE THREAD

**Issue by nifl** [sile-typesetter/sile-typesetter.github.io#6]
I've downloaded the manual from the website and the repo in Safari and Chrome and none of the PDF's can be opened on my mac w/ either Preview or Acrobat.

**Comment by franklinzhang** [comment]
I also have this problem.

**Comment by cyocum** [comment]
I am also seeing this and evince is saying: "PDF document is damaged".  Additionally, running sile on the "sile.sil" file returns "libtexpdf:fatal: Invalid font: -1 (7)"

**Comment by larkvirtual** [comment]
The same for me :-(

P.S. It's pitty documentation unavailable sometimes and generic users have problems building Sile from sources.

**Comment by simoncozens** [comment]
Yeah, sorry, I checked in a bad build and then went on holiday. Will fix when I get back, and also fix so that the web site references a released build of the manual instead of the repository head.

By the way, generic users should not be using bleeding-edge repository builds of this (or indeed any other) project. Stick to releases!

**Comment by simoncozens** [comment]
And this is now fixed.
